# spring:
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: omaressam.ee12@gmail.com
#     password: omaressam12
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
#             required: true
spring:
  mail:
    host: ab-group.host
    port: 465
    username: reservation@ab-group.host
    password: reservation_123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

logging:
  level:
    root: INFO
  file:
    name: app.log
